CapaPresentacion/Controllers/EquiposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class EquiposController : Controller
    {
        // GET: Equipos
        public ActionResult Index()
        {
            return View();
        }
    }
}

CapaPresentacion/Controllers/OrdenServicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    public class OrdenServicioController : Controller
    {
        // GET: OrdenServicio
        public ActionResult Index()
        {
            return View();
        }
    }
}

CapaPresentacion/Views/Shared/_Layout.cshtml
@using CapaEntidades;

@{
    entUsuarios u = (entUsuarios)Session["Usuario"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>PC ZOLUXIONS</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/Bootstrap/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("MenuPrincipal","Intranet")">PC ZOLUXIONS</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Cerrar Sesión</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("MenuPrincipal","Intranet")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Menu Principal
                        </a>
                        <div class="sb-sidenav-menu-heading">Estructuración</div>
                        <a class="nav-link" href="@Url.Action("MenuPrincipal","Intranet")">
                            <div class="sb-nav-link-icon"><i class="fas fa-computer"></i></div>
                            Registrar Equipos
                        </a>
                        <a class="nav-link collapsed" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Mantenedores
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="@Url.Action("Lista","Usuarios")" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Usuarios
                                    <div class="sb-sidenav-collapse-arrow"></div>
                                </a>
                                <a class="nav-link collapsed" href="@Url.Action("Lista","Clientes")" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Clientes
                                    <div class="sb-sidenav-collapse-arrow"></div>
                                </a>
                                <a class="nav-link collapsed" href="@Url.Action("Lista","Servicios")" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Servicios
                                    <div class="sb-sidenav-collapse-arrow"></div>
                                </a>
                                <a class="nav-link collapsed" href="@Url.Action("Lista","Equipos")" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Equipos
                                    <div class="sb-sidenav-collapse-arrow"></div>
                                </a>

                                <a class="nav-link collapsed" href="@Url.Action("Lista","OrdenServicio")" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Orden de servicios
                                    <div class="sb-sidenav-collapse-arrow"></div>
                                </a>
                            </nav>
                        </div>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Iniciaste sesión como:</div>
                    @u.Nombres @u.Apellidos
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; PC ZOLUXIONS Website 2024</div>
                        <div>
                            <a href="#">Politicas de Privacidad</a>
                            &middot;
                            <a href="#">Terminos &amp; Condiciones</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Bootstrap/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/Bootstrap/js/datatables-simple-demo.js"></script>
</body>
</html>